/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookmanager;

import java.util.Set;

/**
 *
 * @author sonki
 */
public class List_book_details extends javax.swing.JFrame {
    private BookManager bookManager;
    /**
     * Creates new form List_book_details
     */
    public List_book_details() {
        initComponents();
        bookManager = new BookManager();
        setTitle("List book details");
        // Gọi phương thức để cập nhật danh sách ID khi form được khởi tạo
        updateBookList();
        Authors_show.setEditable(false);
        Title_show.setEditable(false);
        Date_show.setEditable(false);
        Categories_show.setEditable(false);
    }
    private void updateBookList() {
        // Đọc danh sách sách từ file khi cần cập nhật
        bookManager.loadFromFile("books.dat");
        // Lấy danh sách ID sách từ BookManager
        Set<String> bookIds = bookManager.getAllBookIds();

        // Chuyển danh sách ID thành mảng
        String[] bookIdArray = bookIds.toArray(new String[0]);

        // Thiết lập mô hình cho JList
        List_id_book.setModel(new javax.swing.AbstractListModel<String>() {
            public int getSize() {
                return bookIdArray.length;
            }

            public String getElementAt(int i) {
                return bookIdArray[i];
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        List_id_book = new javax.swing.JList<>();
        Authors_title = new javax.swing.JLabel();
        Title_title = new javax.swing.JLabel();
        Date_title = new javax.swing.JLabel();
        Categories_title = new javax.swing.JLabel();
        Show_book = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        Authors_show = new javax.swing.JTextField();
        Title_show = new javax.swing.JTextField();
        Date_show = new javax.swing.JTextField();
        Categories_show = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(List_id_book);

        Authors_title.setText("Authors");

        Title_title.setText("Title");

        Date_title.setText("Date of  publication");

        Categories_title.setText("Categories");

        Show_book.setText("Show");
        Show_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_bookActionPerformed(evt);
            }
        });

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        Authors_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Authors_showActionPerformed(evt);
            }
        });

        Title_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Title_showActionPerformed(evt);
            }
        });

        Date_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_showActionPerformed(evt);
            }
        });

        Categories_show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Categories_showActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Categories_title)
                            .addComponent(Date_title)
                            .addComponent(Authors_title, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title_title, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Authors_show, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(Title_show)
                            .addComponent(Date_show)
                            .addComponent(Categories_show)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Show_book)
                        .addGap(97, 97, 97)
                        .addComponent(Close)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Authors_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Authors_show, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Title_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Title_show, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Date_show, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Categories_title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Categories_show, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Show_book)
                    .addComponent(Close))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void showBookDetails() {
        // Lấy id sách được chọn từ JList
        String selectedBookId = List_id_book.getSelectedValue();

        // Kiểm tra xem có sách được chọn hay không
        if (selectedBookId != null) {
            // Sử dụng BookManager để lấy thông tin sách
            Book selectedBook = bookManager.getBookById(selectedBookId);

            // Hiển thị thông tin sách trên các JTextField tương ứng
            Authors_show.setText(selectedBook.getAuthor());
            Title_show.setText(selectedBook.getTitle());
            Date_show.setText(selectedBook.getPublicationDate());
            Categories_show.setText(selectedBook.getCategories());
        }
    }
    
    private void Title_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Title_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Title_showActionPerformed

    private void Authors_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Authors_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Authors_showActionPerformed

    private void Date_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_showActionPerformed

    private void Categories_showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Categories_showActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Categories_showActionPerformed

    private void Show_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_bookActionPerformed
        showBookDetails();
    }//GEN-LAST:event_Show_bookActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(List_book_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(List_book_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(List_book_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(List_book_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new List_book_details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Authors_show;
    private javax.swing.JLabel Authors_title;
    private javax.swing.JTextField Categories_show;
    private javax.swing.JLabel Categories_title;
    private javax.swing.JButton Close;
    private javax.swing.JTextField Date_show;
    private javax.swing.JLabel Date_title;
    private javax.swing.JList<String> List_id_book;
    private javax.swing.JButton Show_book;
    private javax.swing.JTextField Title_show;
    private javax.swing.JLabel Title_title;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
