/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.de5;

import java.io.File;
import java.io.PrintWriter;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author sonki
 */
public class jframe extends javax.swing.JFrame {
    private ArrayList<SinhVienATTT> danhsachATTT;
    private ArrayList<SinhVienMatMa> danhsachMM;
    /**
     * Creates new form jframe
     */
    public jframe() {
        initComponents();
        danhsachATTT = new ArrayList<>();
        danhsachMM= new ArrayList<>();
        setLocationRelativeTo(null);
    }
    private void hienthiATTT(){
        String msvATTT= text_msvATTT.getText();
        String hotenATTT= text_hotenATTT.getText();
        String ngaysinhATTT=text_ngaysinhATTT.getText();
        String gioitinhAT=gioitinhATTT.getSelectedItem().toString();
        float diemtbATTT=Float.parseFloat(text_diemATTT.getText());
        float hocphiATTT= Float.parseFloat(text_hocphiATTT.getText());
        SinhVienATTT sinhvienATTT = new SinhVienATTT(hocphiATTT,msvATTT,hotenATTT,ngaysinhATTT,gioitinhAT,diemtbATTT);
        danhsachATTT.add(sinhvienATTT) ;
        System.out.println(sinhvienATTT);
        
    }
    private void ghifileATTT(){
        try(PrintWriter write = new PrintWriter(new File("svat.dat")) ){
            for(SinhVienATTT sinhvienATTT : danhsachATTT){
                write.println(sinhvienATTT.toString());
            }
            JOptionPane.showMessageDialog(rootPane, "ghi file thành công");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    private void hienthiMM(){
        String msvMM= text_masinhvienMM.getText();
        String hotenMM= text_hotenMM.getText();
        String ngaysinhMM=text_ngaysinhMM.getText();
        String gioitinhMM=gioitinh_MM.getSelectedItem().toString();
        float diemtbMM=Float.parseFloat(text_diemtbMM.getText());
        String donviMM=text_donviMM.getText();
        float luongMM= Float.parseFloat(text_luongMM.getText());
        SinhVienMatMa sinhvienMM = new SinhVienMatMa(donviMM,luongMM,msvMM,hotenMM,ngaysinhMM,gioitinhMM,diemtbMM);
        danhsachMM.add(sinhvienMM) ;
        System.out.println(sinhvienMM);
        
    }  
    private void ghifileMM(){
        try(PrintWriter write = new PrintWriter(new File("svmm.dat")) ){
            for(SinhVienMatMa sinhvienMM : danhsachMM){
                write.println(sinhvienMM.toString());
            }
            JOptionPane.showMessageDialog(rootPane, "ghi file thành công");
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_msvATTT = new javax.swing.JTextField();
        text_hotenATTT = new javax.swing.JTextField();
        text_ngaysinhATTT = new javax.swing.JTextField();
        gioitinhATTT = new javax.swing.JComboBox<>();
        text_diemATTT = new javax.swing.JTextField();
        text_hocphiATTT = new javax.swing.JTextField();
        ghifileATTT = new javax.swing.JButton();
        lammoiATTT = new javax.swing.JButton();
        themATTT = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_masinhvienMM = new javax.swing.JTextField();
        text_hotenMM = new javax.swing.JTextField();
        text_ngaysinhMM = new javax.swing.JTextField();
        gioitinh_MM = new javax.swing.JComboBox<>();
        text_diemtbMM = new javax.swing.JTextField();
        text_donviMM = new javax.swing.JTextField();
        ghifileMM = new javax.swing.JButton();
        lammoiMM = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        text_luongMM = new javax.swing.JTextField();
        them = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setVerifyInputWhenFocusTarget(false);

        jLabel1.setText("Mã Sinh Viên");
        jLabel1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setText("Họ Tên ");
        jLabel2.setVerifyInputWhenFocusTarget(false);

        jLabel3.setText("Ngày Sinh");
        jLabel3.setVerifyInputWhenFocusTarget(false);

        jLabel4.setText("Giới  Tính");
        jLabel4.setVerifyInputWhenFocusTarget(false);

        jLabel5.setText("Điểm Trung Bình");
        jLabel5.setVerifyInputWhenFocusTarget(false);

        jLabel6.setText("Học Phí");
        jLabel6.setVerifyInputWhenFocusTarget(false);

        gioitinhATTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        ghifileATTT.setText("Lưu file");
        ghifileATTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghifileATTTActionPerformed(evt);
            }
        });

        lammoiATTT.setText("Làm mới");
        lammoiATTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lammoiATTTActionPerformed(evt);
            }
        });

        themATTT.setText("Thêm ");
        themATTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themATTTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_msvATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_hotenATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_ngaysinhATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gioitinhATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_diemATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text_hocphiATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(themATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(ghifileATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lammoiATTT, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(text_msvATTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(text_hotenATTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(text_ngaysinhATTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(gioitinhATTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(text_diemATTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(text_hocphiATTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ghifileATTT)
                    .addComponent(lammoiATTT)
                    .addComponent(themATTT))
                .addGap(38, 38, 38))
        );

        jTabbedPane1.addTab("ATTT", jPanel1);

        jPanel3.setVerifyInputWhenFocusTarget(false);

        jLabel7.setText("Mã Sinh Viên");
        jLabel7.setVerifyInputWhenFocusTarget(false);

        jLabel8.setText("Họ Tên ");
        jLabel8.setVerifyInputWhenFocusTarget(false);

        jLabel9.setText("Ngày Sinh");
        jLabel9.setVerifyInputWhenFocusTarget(false);

        jLabel10.setText("Giới  Tính");
        jLabel10.setVerifyInputWhenFocusTarget(false);

        jLabel11.setText("Điểm Trung Bình");
        jLabel11.setVerifyInputWhenFocusTarget(false);

        jLabel12.setText("Đơn Vị");
        jLabel12.setVerifyInputWhenFocusTarget(false);

        gioitinh_MM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        ghifileMM.setText("Lưu file");
        ghifileMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ghifileMMActionPerformed(evt);
            }
        });

        lammoiMM.setText("Làm mới");
        lammoiMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lammoiMMActionPerformed(evt);
            }
        });

        jLabel13.setText("Lương");

        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(them, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(ghifileMM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(lammoiMM, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(77, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(text_luongMM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_masinhvienMM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_hotenMM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_ngaysinhMM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(gioitinh_MM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_diemtbMM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_donviMM, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(text_masinhvienMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(text_hotenMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(text_ngaysinhMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(gioitinh_MM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(text_diemtbMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(text_donviMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(text_luongMM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lammoiMM)
                    .addComponent(them)
                    .addComponent(ghifileMM))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("MM", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ghifileATTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghifileATTTActionPerformed
        // TODO add your handling code here:
        ghifileATTT();
    }//GEN-LAST:event_ghifileATTTActionPerformed

    private void themATTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themATTTActionPerformed
        // TODO add your handling code here:
        hienthiATTT();
    }//GEN-LAST:event_themATTTActionPerformed

    private void lammoiATTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lammoiATTTActionPerformed
        // TODO add your handling code here:
        text_msvATTT.setText("");
        text_hotenATTT.setText("");
        text_ngaysinhATTT.setText("");
        text_diemATTT.setText("");
        text_hocphiATTT.setText("");
        
    }//GEN-LAST:event_lammoiATTTActionPerformed

    private void lammoiMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lammoiMMActionPerformed
        // TODO add your handling code here:text_msvATTT.setText("");
        text_masinhvienMM.setText("");
        text_hotenMM.setText("");
        text_ngaysinhMM.setText("");
        text_diemtbMM.setText("");
        text_donviMM.setText("");
        text_luongMM.setText("");
    }//GEN-LAST:event_lammoiMMActionPerformed

    private void ghifileMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ghifileMMActionPerformed
        // TODO add your handling code here:
        ghifileMM();
    }//GEN-LAST:event_ghifileMMActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        hienthiMM();
    }//GEN-LAST:event_themActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ghifileATTT;
    private javax.swing.JButton ghifileMM;
    private javax.swing.JComboBox<String> gioitinhATTT;
    private javax.swing.JComboBox<String> gioitinh_MM;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton lammoiATTT;
    private javax.swing.JButton lammoiMM;
    private javax.swing.JTextField text_diemATTT;
    private javax.swing.JTextField text_diemtbMM;
    private javax.swing.JTextField text_donviMM;
    private javax.swing.JTextField text_hocphiATTT;
    private javax.swing.JTextField text_hotenATTT;
    private javax.swing.JTextField text_hotenMM;
    private javax.swing.JTextField text_luongMM;
    private javax.swing.JTextField text_masinhvienMM;
    private javax.swing.JTextField text_msvATTT;
    private javax.swing.JTextField text_ngaysinhATTT;
    private javax.swing.JTextField text_ngaysinhMM;
    private javax.swing.JToggleButton them;
    private javax.swing.JToggleButton themATTT;
    // End of variables declaration//GEN-END:variables
}
