/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carsproject.Login;


import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author sonki
 */
public class Change_password extends javax.swing.JFrame {

    /**
     * Creates new form Change_password
     */
    public Change_password() {
        initComponents();
        // chỉ tắt jframe khi nhấn x
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
    private void refreshForm() {
    // Thực hiện các tác vụ làm mới ở đây, ví dụ: clear các trường nhập liệu
        Text_old_password.setText("");
        Text_new_password.setText("");
        Text_confirm_password.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text_old_password = new javax.swing.JPasswordField();
        Text_new_password = new javax.swing.JPasswordField();
        Text_confirm_password = new javax.swing.JPasswordField();
        old_password = new javax.swing.JLabel();
        new_password = new javax.swing.JLabel();
        show_old_password = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        OK = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text_old_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Text_old_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(Text_old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 310, 30));
        getContentPane().add(Text_new_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 310, 30));
        getContentPane().add(Text_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 310, 30));

        old_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        old_password.setText("Nhập mật khẩu cũ:");
        getContentPane().add(old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 129, 33));

        new_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        new_password.setText("Mật khẩu mới:");
        getContentPane().add(new_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 129, 34));

        show_old_password.setBackground(new java.awt.Color(0, 171, 191));
        show_old_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        show_old_password.setText("Hiển thị mật khẩu");
        show_old_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_old_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(show_old_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, -1, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Xác nhận mật khẩu mới:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 36));

        OK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OK.setText("OK");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 410, 109, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Đổi mật khẩu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 224015.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean checkCurrentPassword(String currentPassword) {
    // Lấy mật khẩu hiện tại từ SessionManager
        String storedPassword = SessionManager.getPasswordByUsername(SessionManager.getLoggedInUsername());

    // So sánh mật khẩu nhập vào với mật khẩu từ SessionManager
        return storedPassword != null && storedPassword.equals(currentPassword);
    }
    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
        String oldPassword = new String(Text_old_password.getPassword());
        String newPassword = new String(Text_new_password.getPassword());
        String confirmNewPassword = new String(Text_confirm_password.getPassword());

    // Kiểm tra xem mật khẩu mới có khớp với xác nhận không
    if (!newPassword.equals(confirmNewPassword)) {
        JOptionPane.showMessageDialog(null, "Mật khẩu mới và xác nhận không khớp.");
        refreshForm();
        return;
    }

    // Kiểm tra mật khẩu hiện tại
    if (!checkCurrentPassword(oldPassword)) {
        JOptionPane.showMessageDialog(null, "Mật khẩu hiện tại không đúng.");
        refreshForm();
        return;
    }

    // Lấy tên đăng nhập hiện tại (thay thế điều này bằng logic thực tế của bạn)
    String loggedInUsername = SessionManager.getLoggedInUsername();

    // Cập nhật mật khẩu trong cơ sở dữ liệu
    String updatePasswordQuery = "UPDATE account SET pass = ? WHERE username = ?";
    try {
        Connection conn = Connect_DB.connect();
        PreparedStatement pst = conn.prepareStatement(updatePasswordQuery);
        pst.setString(1, newPassword);
        pst.setString(2, loggedInUsername);
        int rowsAffected = pst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(null, "Đổi mật khẩu thành công.");
            this.dispose();
            // Thêm phần refresh tại đây nếu bạn muốn
        } else {
            JOptionPane.showMessageDialog(null, "Mật khẩu hiện tại không đúng.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, " Mật khẩu mới phải trên 6 kí tự.");
        refreshForm();
    }
    }//GEN-LAST:event_OKActionPerformed

    private void show_old_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_old_passwordActionPerformed
        // TODO add your handling code here:
        if (show_old_password.isSelected()) {
            // Nếu checkbox được chọn, hiển thị mật khẩu cũ
            Text_old_password.setEchoChar((char) 0); // Hiển thị mật khẩu dưới dạng văn bản thường
        } else {
            // Nếu checkbox không được chọn, ẩn mật khẩu cũ
            Text_old_password.setEchoChar('*'); // Ẩn mật khẩu
        }
    }//GEN-LAST:event_show_old_passwordActionPerformed

    private void Text_old_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Text_old_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Text_old_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Change_password.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Change_password().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton OK;
    private javax.swing.JPasswordField Text_confirm_password;
    private javax.swing.JPasswordField Text_new_password;
    private javax.swing.JPasswordField Text_old_password;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel new_password;
    private javax.swing.JLabel old_password;
    private javax.swing.JRadioButton show_old_password;
    // End of variables declaration//GEN-END:variables
}
