/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carsproject.Login;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author sonki
 */
public class New_account extends javax.swing.JFrame {

    /**
     * Creates new form New_account
     */
    public New_account() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        OK = new javax.swing.JButton();
        UserName = new javax.swing.JTextField();
        show_confirm_password = new javax.swing.JRadioButton();
        Show_password = new javax.swing.JRadioButton();
        PassWord = new javax.swing.JPasswordField();
        Confirm_Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OK.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        OK.setText("Xác nhận");
        OK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKActionPerformed(evt);
            }
        });
        getContentPane().add(OK, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 118, -1));

        UserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameActionPerformed(evt);
            }
        });
        getContentPane().add(UserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 162, 250, 30));

        show_confirm_password.setBackground(new java.awt.Color(0, 171, 191));
        show_confirm_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        show_confirm_password.setText("Hiển thị mật khẩu");
        show_confirm_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_confirm_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(show_confirm_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 150, -1));

        Show_password.setBackground(new java.awt.Color(0, 171, 191));
        Show_password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Show_password.setText("Hiển thị mật khẩu");
        Show_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Show_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(Show_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 150, -1));

        PassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassWordActionPerformed(evt);
            }
        });
        getContentPane().add(PassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 222, 250, 30));

        Confirm_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Confirm_PasswordActionPerformed(evt);
            }
        });
        getContentPane().add(Confirm_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 292, 250, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Tên đăng nhập:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Mật khẩu: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Xác nhận mật khẩu:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Tạo tài khoản mới");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 224015.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameActionPerformed

    private void PassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassWordActionPerformed

    private void Confirm_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Confirm_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Confirm_PasswordActionPerformed

    private void OKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKActionPerformed
        // TODO add your handling code here:
         // Lấy thông tin từ các trường dữ liệu
    String username = UserName.getText();
    String password = PassWord.getText();
    String confirmPassword = Confirm_Password.getText();

    // Kiểm tra xem các trường thông tin có rỗng không
    if (username.isEmpty() || password.isEmpty() || confirmPassword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin.");
        return;
    }

    // Kiểm tra xem mật khẩu và mật khẩu xác nhận có giống nhau không
    if (!password.equals(confirmPassword)) {
        JOptionPane.showMessageDialog(this, "Mật khẩu và xác nhận mật khẩu không khớp. Vui lòng kiểm tra lại.");
        return;
    }

    // Thực hiện tạo tài khoản mới
    String sql = "INSERT INTO account (username, pass) VALUES (?, ?)";

    try {
        Connection conn = Connect_DB.connect();
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, username);
        pst.setString(2, password);

        int rowsAffected = pst.executeUpdate();

        if (rowsAffected > 0) {
            JOptionPane.showMessageDialog(this, "Tạo tài khoản thành công!");
             this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Không thể tạo tài khoản. Vui lòng kiểm tra lại thông tin.");
        }

        pst.close();
        conn.close();
    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Tài khoản đã tồn tại.");
    }
    }//GEN-LAST:event_OKActionPerformed

    private void Show_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Show_passwordActionPerformed
        // TODO add your handling code here:
         if ( Show_password.isSelected()) {
            // Nếu checkbox được chọn, hiển thị mật khẩu cũ
            PassWord.setEchoChar((char) 0); // Hiển thị mật khẩu dưới dạng văn bản thường
        } else {
            // Nếu checkbox không được chọn, ẩn mật khẩu cũ
            PassWord.setEchoChar('*'); // Ẩn mật khẩu
        }
    }//GEN-LAST:event_Show_passwordActionPerformed

    private void show_confirm_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_confirm_passwordActionPerformed
        // TODO add your handling code here:
          if ( show_confirm_password.isSelected()) {
            // Nếu checkbox được chọn, hiển thị mật khẩu cũ
            Confirm_Password.setEchoChar((char) 0); // Hiển thị mật khẩu dưới dạng văn bản thường
        } else {
            // Nếu checkbox không được chọn, ẩn mật khẩu cũ
            Confirm_Password.setEchoChar('*'); // Ẩn mật khẩu
        }
    }//GEN-LAST:event_show_confirm_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(New_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(New_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(New_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(New_account.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_account().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Confirm_Password;
    private javax.swing.JButton OK;
    private javax.swing.JPasswordField PassWord;
    private javax.swing.JRadioButton Show_password;
    private javax.swing.JTextField UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton show_confirm_password;
    // End of variables declaration//GEN-END:variables
}
