/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.carsproject;

import com.mycompany.carsproject.Object.Car;
import com.mycompany.carsproject.Object.Car_DAO;
import com.mycompany.carsproject.Object.Car_on_rent;
import com.mycompany.carsproject.Object.Car_on_rent_DAO;
import com.mycompany.carsproject.Object.Customer_DAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author manhl
 */
public class RentalForm extends javax.swing.JFrame {
    Customer_DAO customerDAO = new Customer_DAO();
    /**
     * Creates new form RentalForm
     */
    public RentalForm() {
        initComponents();
        displayActiveCarsOnTable();
        displayActiveCarsOnRentOnTable();
        populateCustomerIDs();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
     private void displayActiveCarsOnTable() {
        Car_DAO carDAO = new Car_DAO();
        List<Car> activeCars = carDAO.getAllActiveCars();
        DefaultTableModel clear = (DefaultTableModel)Avaiable_cars.getModel();
        clear.setRowCount(0);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Rent ID");
        model.addColumn("Brand");
        model.addColumn("Model");
        model.addColumn("License Plate");
        model.addColumn("Price");

        for (Car car : activeCars) {
            model.addRow(new Object[]{
                    car.getCarID(),
                    car.getBrand(),
                    car.getModel(),
                    car.getLicensePlate(),
                    car.getPrice()
            });
        }

        Avaiable_cars.setModel(model);
    }
      private void displayActiveCarsOnRentOnTable() {
        Car_on_rent_DAO car_rentedDAO = new Car_on_rent_DAO();
        List<Car_on_rent> Cars_rented = car_rentedDAO.getAllCarOnRentWithFeesFromFunction();
        DefaultTableModel clear = (DefaultTableModel)Cars_on_rent.getModel();
        clear.setRowCount(0);
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Rent ID");
        model.addColumn("Car ID");
        model.addColumn("Customer ID");
        model.addColumn("Ngày thuê");
        model.addColumn("Ngày hẹn trả");
        model.addColumn("Tổng tiền");
        
        for (Car_on_rent car : Cars_rented) {
            model.addRow(new Object[]{
                    car.getRentID(),
                    car.getCarID(),
                    car.getCustomerID(),
                    car.getRentDate(),
                    car.getReturnDate(),
                    car.getPrice()
            });
        }

        Cars_on_rent.setModel(model);
    }
    private void populateCustomerIDs() {
    // Get all customer IDs from the database
        List<String> customerIDs = customerDAO.getAllCustomerIDs();

        // Clear existing items in the JComboBox
        Customer_ID.removeAllItems();

    // Add retrieved customer IDs to the JComboBox
        for (String customerID : customerIDs) {
            Customer_ID.addItem(customerID);
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Rent_ID = new javax.swing.JTextField();
        Car_ID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Customer_ID = new javax.swing.JComboBox<>();
        Rent = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cars_on_rent = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Avaiable_cars = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PRICE_SUM = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Rent_date = new com.toedter.calendar.JDateChooser();
        Return_date = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Thuê Xe");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(481, 22, -1, -1));

        jLabel2.setText("Mã hóa đơn");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        Rent_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rent_IDActionPerformed(evt);
            }
        });
        getContentPane().add(Rent_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 113, -1));

        Car_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Car_IDActionPerformed(evt);
            }
        });
        getContentPane().add(Car_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 113, -1));

        jLabel3.setText("Mã xe");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel4.setText("Mã khách hàng");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel5.setText("Ngày thuê");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel6.setText("Ngày hẹn trả");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 76, -1));

        Customer_ID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Customer_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_IDActionPerformed(evt);
            }
        });
        getContentPane().add(Customer_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 113, -1));

        Rent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-car-rental-20.png"))); // NOI18N
        Rent.setText("     Thuê");
        Rent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RentActionPerformed(evt);
            }
        });
        getContentPane().add(Rent, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 118, 41));

        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-update-file-24.png"))); // NOI18N
        Update.setText("Làm mới");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        getContentPane().add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 118, 44));

        Back.setText("< Trở về");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 14, 118, 42));

        Cars_on_rent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã hóa đơn", "Mã xe", "Mã khách hàng", "Ngày thuê", "Ngày hẹn trả", "Tổng"
            }
        ));
        jScrollPane1.setViewportView(Cars_on_rent);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 990, 267));

        Avaiable_cars.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã xe", "Nhãn hiệu", "Dòng", "Biển kiếm soát", "Giá"
            }
        ));
        Avaiable_cars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Avaiable_carsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(Avaiable_cars);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 688, 363));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Xe có sẵn");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Xe đang được thuê");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 184, -1));

        jLabel7.setText("Giá thuê (1 ngày)");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));
        getContentPane().add(PRICE_SUM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 113, -1));

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 982, -1, 32));
        getContentPane().add(Rent_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 113, -1));
        getContentPane().add(Return_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 113, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 221713.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, 360));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 221713.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 180, 360));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 221713.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 180, 360));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 221713.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 180, 360));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 221452.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 950, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 221452.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 950, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 221452.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, -1));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Screenshot 2023-12-23 221452.png"))); // NOI18N
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 950, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
         choiceForm choiceform = new choiceForm();

    // Hiển thị JFrame manageCustomers
        choiceform.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    private void RentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RentActionPerformed
        // TODO add your handling code here:
                                           
    // Lấy dữ liệu từ các thành phần trên giao diện
        String carID = Car_ID.getText();
        String customerID = (String) Customer_ID.getSelectedItem();
        String rentID = Rent_ID.getText();
        java.sql.Date rentDate;
        java.sql.Date returnDate;
        if(Rent_date.getDate()==null || Return_date.getDate()==null)
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ ngày");
        }
        else{
        rentDate = new java.sql.Date(Rent_date.getDate().getTime());
        returnDate = new java.sql.Date(Return_date.getDate().getTime()); 
        
        while(true)
        {
            if(carID.isBlank() || customerID.isBlank() || rentID.isBlank())
            {
                JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin");
                break;
            }
            if(rentDate.after(returnDate))
            {
                JOptionPane.showMessageDialog(this, "Ngày hẹn trả không được nhỏ hơn ngày thuê");
                break;
            }
            else
            {
            // Tạo đối tượng Car_on_rent
                Car_on_rent carOnRent = new Car_on_rent(carID, customerID, rentID, rentDate, returnDate);

        // Thêm hóa đơn thông qua đối tượng DAO
                Car_on_rent_DAO carOnRentDAO = new Car_on_rent_DAO();
                carOnRentDAO.addCarOnRent(carOnRent);
                jLabel10.setText("");

        // Cập nhật lại bảng Cars_on_rent (nếu cần)
                displayActiveCarsOnTable();
                displayActiveCarsOnRentOnTable();
                break;
            }
        }

    //updateCarsOnRentTable(); // Hàm này cần phải được triển khai để cập nhật hiển thị trên bảng Cars_on_rent
        }
    }//GEN-LAST:event_RentActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        Rent_ID.setText("");
        Car_ID.setText("");
        Customer_ID.setSelectedIndex(0);
        Rent_date.setDate(null);
        Return_date.setDate(null);
        PRICE_SUM.setText("");
    
    }//GEN-LAST:event_UpdateActionPerformed

    private void Customer_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_IDActionPerformed

    private void Car_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Car_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Car_IDActionPerformed
      
    
    private void Avaiable_carsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Avaiable_carsMouseClicked
        // TODO add your handling code here:
        int selectedRow = Avaiable_cars.getSelectedRow();

        if (selectedRow != -1) {
        // Lấy giá trị của cột Car ID (giả sử là cột thứ 0)
            Object carIDObject = Avaiable_cars.getValueAt(selectedRow, 0);
            Object PRICEObject = Avaiable_cars.getValueAt(selectedRow, 4);
//            java.sql.Date rentDate = new java.sql.Date(Rent_date.getDate().getTime());
//            java.sql.Date returnDate = new java.sql.Date(Return_date.getDate().getTime());
            
            if (carIDObject != null) {
                String carID = carIDObject.toString();
                Car_ID.setText(carID);
                String price = PRICEObject.toString();
                PRICE_SUM.setText(price);
            }
        }
    }//GEN-LAST:event_Avaiable_carsMouseClicked

    private void Rent_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rent_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rent_IDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RentalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RentalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Avaiable_cars;
    private javax.swing.JButton Back;
    private javax.swing.JTextField Car_ID;
    private javax.swing.JTable Cars_on_rent;
    private javax.swing.JComboBox<String> Customer_ID;
    private javax.swing.JTextField PRICE_SUM;
    private javax.swing.JButton Rent;
    private javax.swing.JTextField Rent_ID;
    private com.toedter.calendar.JDateChooser Rent_date;
    private com.toedter.calendar.JDateChooser Return_date;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}